name: Test Automation CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

run-name: >
  Branch run → ${{ github.ref_name }}

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Build with Gradle (without test execution)
        run: ./gradlew clean assemble

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Tests with Gradle
        run: ./gradlew clean test

      - name: Verify Test Reports Exist
        if: always()
        run: |
          if [ ! -f build/reports/ExtentReport.html ]; then
            echo "File 'build/reports/ExtentReport.html' does not exist."
          fi
          echo "File 'build/reports/ExtentReport.html' exists."

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: build/reports/ExtentReport.html